# **CLASSIFICATION USING DNN**

In [3]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

In [4]:
dataset=loadtxt('/content/pima-indians-diabetes.csv',delimiter=',')
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [5]:
X=dataset[:,0:8]
Y=dataset[:,8]
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [6]:
Y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [7]:
#Creating model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

#Compiling and fitting model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y, epochs=150, batch_size=10)

Epoch 1/150
77/77 [==============================] - 2s 20ms/step - loss: 6.7564 - accuracy: 0.4284
Epoch 2/150
77/77 [==============================] - 0s 3ms/step - loss: 0.9087 - accuracy: 0.5716
Epoch 3/150
77/77 [==============================] - 0s 3ms/step - loss: 0.7697 - accuracy: 0.6263
Epoch 4/150
77/77 [==============================] - 0s 3ms/step - loss: 0.7351 - accuracy: 0.6276
Epoch 5/150
77/77 [==============================] - 0s 3ms/step - loss: 0.6998 - accuracy: 0.6536
Epoch 6/150
77/77 [==============================] - 0s 3ms/step - loss: 0.6906 - accuracy: 0.6315
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6699 - accuracy: 0.6484
Epoch 8/150
77/77 [==============================] - 0s 6ms/step - loss: 0.6640 - accuracy: 0.6497
Epoch 9/150
77/77 [==============================] - 0s 3ms/step - loss: 0.6534 - accuracy: 0.6602
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6370 - accuracy: 0.6576
Epoch 11

In [8]:
model.fit(X, Y, epochs=150, batch_size=10)
predictions = model.predict(X)
rounded = [round(x[0]) for x in predictions]
print(rounded)
scores = model.evaluate(X, Y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

Epoch 1/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5202 - accuracy: 0.7422
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5039 - accuracy: 0.7526
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5024 - accuracy: 0.7643
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5122 - accuracy: 0.7396
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 0.4908 - accuracy: 0.7656
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.4939 - accuracy: 0.7604
Epoch 7/150
77/77 [==============================] - 0s 3ms/step - loss: 0.4946 - accuracy: 0.7643
Epoch 8/150
77/77 [==============================] - 1s 11ms/step - loss: 0.5010 - accuracy: 0.7487
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5072 - accuracy: 0.7695
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.4907 - accuracy: 0.7669
Epoch 11