# **Practical 1 : Matrix Multiplication, Eigen Vectors, Eigenvalues Computation using TensorFlow**

**Matrix Multiplication**

In [1]:
import tensorflow as tf

In [2]:
x=tf.constant([1,2,3,4,5,6],shape=[2,3])
print(x)
y=tf.constant([7,8,9,10,11,12],shape=[3,2])
print(y)
z=tf.matmul(x,y)
print("Product:",z) 

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
Product: tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


**Eigen Vectors, Eigenvalues**

In [3]:
e_matrix_A=tf.random.uniform([2,2],minval=3,maxval=10,dtype=tf.float32,name="matrixA")
print("Matrix A:\n{}\n\n".format(e_matrix_A))
eigen_values_A,eigen_vectors_A=tf.linalg.eigh(e_matrix_A)
print("Eigen Vectors:\n{}\n\nEigen values:\n{}\n".format(eigen_vectors_A, eigen_values_A))

Matrix A:
[[9.044746  4.1768036]
 [3.8888688 7.3167267]]


Eigen Vectors:
[[-0.625745    0.78002775]
 [ 0.78002775  0.625745  ]]

Eigen values:
[ 4.1970434 12.164432 ]

